

usedSharedRessources = {
    'marvinGui': [
        'ProcessDict',
        'ArduinoDict',
        'ServoTypeDict',
        'ServoStaticDict',
        'ServoDerivedDict',
        'ServoCurrentDict',
        'CartDict',

        'SharedDataUpdateQueue',
        'SkeletonGuiUpdateQueue',
        'CartGuiUpdateQueue',
        'IkUpdateQueue',
        'ServoRequestQueue',
        'CartRequestQueue',
        'SpeakRequestQueue',
        'SpeakRespondQueue',
        'ImageProcessingQueue',
    ],

    'skeletonControl': [
        'ProcessDict',
        #'ArduinoDict',
        'ServoTypeDict',
        'ServoStaticDict',
        'ServoDerivedDict',
        'ServoCurrentDict',
        #'CartDict'
        'SharedDataUpdateQueue',
        'SkeletonGuiUpdateQueue',
        #'CartGuiUpdateQueue',
        'IkUpdateQueue',
        'ServoRequestQueue',
        #'CartRequestQueue',
        'SpeakRequestQueue',
        #'SpeakRespondQueue',
        'ImageProcessingQueue',
    ],

    'cartControl': [
        'ProcessDict',
        #'ArduinoDict',
        #'ServoTypeDict',
        #'ServoStaticDict',
        #'ServoDerivedDict',
        'ServoCurrentDict',
        #'CartDict'
        'SharedDataUpdateQueue',
        #'SkeletonGuiUpdateQueue',
        'CartGuiUpdateQueue',
        #'IkUpdateQueue',
        'ServoRequestQueue',
        'CartRequestQueue',
        #'SpeakRequestQueue',
        # 'SpeakRespondQueue',
        'ImageProcessingQueue',
    ],

    'randomMoves': [
        'ProcessDict',
        # 'ArduinoDict',
        # 'ServoTypeDict',
        'ServoStaticDict',
        # 'ServoDerivedDict',
        'ServoCurrentDict',
        # 'CartDict',

        'SharedDataUpdateQueue',
        # 'SkeletonGuiUpdateQueue',
        # 'CartGuiUpdateQueue',
        # 'IkUpdateQueue',
        'ServoRequestQueue',
        # 'CartRequestQueue',
        'SpeakRequestQueue',
        # 'SpeakRespondQueue',
        # 'ImageProcessingQueue',
        ],

    'playGesture': [
        'ProcessDict',
        # 'ArduinoDict',
        # 'ServoTypeDict',
        # 'ServoStaticDict',
        # 'ServoDerivedDict',
        'ServoCurrentDict',
        # 'CartDict',

        'SharedDataUpdateQueue',
        # 'SkeletonGuiUpdateQueue',
        # 'CartGuiUpdateQueue',
        # 'IkUpdateQueue',
        'ServoRequestQueue',
        # 'CartRequestQueue',
        'SpeakRequestQueue',
        # 'SpeakRespondQueue',
        # 'ImageProcessingQueue'
    ],
    'speechControl': [
        'ProcessDict',
        # 'ArduinoDict',
        # 'ServoTypeDict',
        'ServoStaticDict',
        # 'ServoDerivedDict',
        #'ServoCurrentDict',
        # 'CartDict',

        #'SharedDataUpdateQueue',
        # 'SkeletonGuiUpdateQueue',
        # 'CartGuiUpdateQueue',
        # 'IkUpdateQueue',
        'ServoRequestQueue',
        # 'CartRequestQueue',
        'SpeakRequestQueue',
        # 'SpeakRespondQueue',
        # 'ImageProcessingQueue'
    ],
    'imageProcessing': [
        'ProcessDict',
        # 'ArduinoDict',
        # 'ServoTypeDict',
        # 'ServoStaticDict',
        # 'ServoDerivedDict',
        # 'ServoCurrentDict',
        # 'CartDict',

        'SharedDataUpdateQueue',
        # 'SkeletonGuiUpdateQueue',
        # 'CartGuiUpdateQueue',
        # 'IkUpdateQueue',
        #'ServoRequestQueue',
        # 'CartRequestQueue',
        #'SpeakRequestQueue',
        # 'SpeakRespondQueue',
        'ImageProcessingQueue'
    ],

}
